version: "3"
services:
  web:
    build:
      context: ./api
    ports:
      - 9000:9000
  frontend:
    build:
      context: ./client
      dockerfile: dockerfile_dev
    ports:
      - 3000:3000
